### ISSUE TITLE
DIY脚本"jd_factory_component.js"有报错

### ISSUE THREAD

**Issue by WriteMemory** [SuperManito/JD-FreeFuck#170]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：
DIY脚本"jd_factory_component.js"有报错

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
```
开始【京东账号3】jd_xxxxxx

获取用户信息：OK


❗️京喜工厂plus, 错误!
TypeError: Cannot read property '0' of null
    at /jd/scripts/jd_factory_component.js:96:35
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_factory_component.js:380:4794)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

获取自己零件：OK


拾取自己零件：好可惜,没中奖哦~，获得电力 0


获取工厂好友：OK


获取好友零件：OK


获取好友零件：OK


获取好友零件：OK


获取好友零件：OK


获取好友零件：OK


获取好友零件：OK


拾取好友零件：好可惜,没中奖哦~，获得电力 0


获取用户信息：OK


❗️京喜工厂plus, 错误!
TypeError: Cannot read property '0' of null
    at /jd/scripts/jd_factory_component.js:96:35
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_factory_component.js:380:4794)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️京喜工厂plus, 错误!
TypeError: Cannot read property 'user' of undefined
    at /jd/scripts/jd_factory_component.js:60:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by SuperManito** [comment]
脚本没问题，黑号
