### ISSUE TITLE
求助大佬，美丽研究院运行失败

### ISSUE THREAD

**Issue by qin369** [SuperManito/JD-FreeFuck#203]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [ ] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：每次运行美丽研究院，都提示API请求失败。一键执行所有活动脚本与手动运行脚本均有同样错误提示。
其他任务都可以运行的。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：美丽研究院, 开始!

====================共4个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/19/2021, 10:02:10 AM=====================

******开始【京东账号1】Skylee99*********

AAEAIJpNXvntlrSwCMyKaIKNqfVLG48QIcA1c-Yt5-gckA9c0
AAFgVAYxADAfpweKT_wqLSnM0DAHI-tz_FAk0IonRrf2fypJljnrrg5_YXCYigxU9HNCMDXfir8
"Response code 403 (Forbidden)"
美丽研究院 API请求失败，请检查网路重试
wss://xinruimz-isv.isvjcloud.com/wss/?token=undefined
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (/opt/jd/scripts/node_modules/ws/lib/websocket.js:604:7)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (/opt/jd/scripts/node_modules/ws/lib/websocket.js:722:15)
    at ClientRequest.<anonymous> (/opt/jd/scripts/node_modules/ws/lib/websocket.js:604:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

**Comment by nxcjs** [comment]
我也是很少成功，得过且过了发送自我的盖乐世
