### ISSUE TITLE
美丽研究院 API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by piaoyun** [SuperManito/JD-FreeFuck#207]
美丽研究院 API请求失败，请检查网路重试
wss://xinruimz-isv.isvjcloud.com/wss/?token=undefined

直接运行不了。

**Comment by piaoyun** [comment]
```
root@VM-0-8-ubuntu:/opt/jd# bash jd.sh jd_beauty now

🔔美丽研究院, 开始!

====================共10个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/19/2021, 4:44:04 PM=====================


******开始【京东账号1】嗷嗷嗷*********

AAEAIBySFrV2ZJFfRasfaf3-OLGpgba7GZ4Ra9nu0
AAFgVGRVADdsafasggHyksjXg9w2fsafzQpaYQ6PHwpFbk
"Response code 403 (Forbidden)"
美丽研究院 API请求失败，请检查网路重试
wss://xinruimz-isv.isvjcloud.com/wss/?token=undefined
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (/opt/jd/scripts/node_modules/ws/lib/websocket.js:604:7)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (/opt/jd/scripts/node_modules/ws/lib/websocket.js:722:15)
    at ClientRequest.<anonymous> (/opt/jd/scripts/node_modules/ws/lib/websocket.js:604:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
```

没有走代理，国内的服务器呢。
