### ISSUE TITLE
什么情况 windows ubuntu 

### ISSUE THREAD

**Issue by hello1983** [SuperManito/JD-FreeFuck#88]
`您secret设置的取关参数:
["","","",""]
(node:16652) UnhandledPromiseRejectionWarning: TypeError: this.got(...).on is not a function
    at Object.get (/opt/jd/scripts/jd_unsubscribe.js:350:4593)
    at Promise (/opt/jd/scripts/jd_unsubscribe.js:144:7)
    at new Promise (<anonymous>)
    at getFollowGoods (/opt/jd/scripts/jd_unsubscribe.js:130:10)
    at Promise (/opt/jd/scripts/jd_unsubscribe.js:94:29)
    at new Promise (<anonymous>)
    at unsubscribeGoods (/opt/jd/scripts/jd_unsubscribe.js:93:10)
    at jdUnsubscribe (/opt/jd/scripts/jd_unsubscribe.js:77:5)
    at /opt/jd/scripts/jd_unsubscribe.js:64:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:16652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16652) UnhandledPromiseRejectionWarning: TypeError: this.got(...).on is not a function
    at Object.get (/opt/jd/scripts/jd_unsubscribe.js:350:4593)
    at Promise (/opt/jd/scripts/jd_unsubscribe.js:235:7)
    at new Promise (<anonymous>)
    at getFollowShops (/opt/jd/scripts/jd_unsubscribe.js:221:10)
    at Promise (/opt/jd/scripts/jd_unsubscribe.js:188:29)
    at new Promise (<anonymous>)
    at unsubscribeShops (/opt/jd/scripts/jd_unsubscribe.js:187:10)
    at jdUnsubscribe (/opt/jd/scripts/jd_unsubscribe.js:78:5)
    at /opt/jd/scripts/jd_unsubscribe.js:64:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:16652) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.req.once.err (/usr/lib/nodejs/got/index.js:111:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:16652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:16652) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.req.once.err (/usr/lib/nodejs/got/index.js:111:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:16652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`

**Comment by SuperManito** [comment]
你的linux咋这么特殊，这报错我都没见过，发完整的日志

**Comment by hello1983** [comment]
> 你的linux咋这么特殊，这报错我都没见过，发完整的日志

更新一下  sh manual-update.sh 可以啦！谢谢

**Comment by SuperManito** [comment]
> > 你的linux咋这么特殊，这报错我都没见过，发完整的日志
> 
> 更新一下 sh manual-update.sh 可以啦！谢谢

好的
